#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ACTION="${1:-submit}"

SOURCE_DATA_ROOT="${SOURCE_DATA_ROOT:-/ceph/srv/dwong/training_samples_h5}"
COMPACT_DATA_ROOT="${COMPACT_DATA_ROOT:-$REPO_ROOT/.condor_data/compact_l40s}"
ENERGIES="${ENERGIES:-10,20,50,100,200,500}"
EVENTS_PER_GROUP="${EVENTS_PER_GROUP:-10}"
NUM_EPOCHS="${NUM_EPOCHS:-20}"
RUN_STAMP="$(date +%Y%m%d_%H%M%S)"
JOB_NAME="${JOB_NAME:-pairwise_compact_l40s}"
RUN_NAME="${RUN_NAME:-${JOB_NAME}_${RUN_STAMP}}"
GENERATED_JDL="$SCRIPT_DIR/submit.generated.jdl"
LATEST_FILE="$SCRIPT_DIR/latest_job.txt"

cd "$REPO_ROOT"

prepare_dataset() {
    .venv/bin/python scripts/prepare_compact_h5_dataset.py \
        --source "$SOURCE_DATA_ROOT" \
        --destination "$COMPACT_DATA_ROOT" \
        --energies "$ENERGIES" \
        --events-per-group "$EVENTS_PER_GROUP"
}

build_transfer_list() {
    local -n output=$1
    output=(run.sh scripts reconstruction_model uv.lock pyproject.toml)
    while IFS= read -r path; do
        output+=("$path")
    done < <(
        find "$COMPACT_DATA_ROOT" -type f -name '*_traces_energy_*_batch_*.h5' \
            | sort
    )

    expected_files=$((2 * 6))
    actual_files=$(printf '%s\n' "${output[@]}" | grep -c '\.h5$' || true)
    if [ "$actual_files" -ne "$expected_files" ]; then
        echo "ERROR: Found $actual_files compact H5 files, expected $expected_files." >&2
        exit 1
    fi
}

join_csv() {
    local IFS=", "
    echo "$*"
}

write_jdl() {
    local transfer_files=("$@")
    local transfer_csv wandb_mode wandb_run wandb_artifacts
    transfer_csv="$(join_csv "${transfer_files[@]}")"

    if [ -n "${WANDB_API_KEY:-}" ]; then
        wandb_mode="online"
        wandb_run=1
        wandb_artifacts=1
    else
        wandb_mode="disabled"
        wandb_run=0
        wandb_artifacts=0
    fi

    cat > "$GENERATED_JDL" <<EOF
# Generated by scripts/train_compact_l40s/submit.sh
Executable = /bin/sh
Arguments = run.sh

Output = scripts/train_compact_l40s/train.\$(Cluster).out
Error = scripts/train_compact_l40s/train.\$(Cluster).err
Log = scripts/train_compact_l40s/train.\$(Cluster).log
stream_output = True
stream_error = True

transfer_input_files = ${transfer_csv}
transfer_output_files = artifacts, training_job_summary.json
transfer_output_remaps = "training_job_summary.json=scripts/train_compact_l40s/training_job_summary.\$(Cluster).json"
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

+RequestWalltime = 43200
RequestCPUs = 8
RequestMemory = 64000
request_disk = 50000000
request_GPUs = 1
+RemoteJob = True
use_x509userproxy = False
requirements = (TARGET.CloudSite =?= "BwForCluster-Nemo2") && (TARGET.GPUs_DeviceName =?= "NVIDIA L40S")
accounting_group = delight

Universe = vanilla
+SingularityImage = "docker://cverstege/alma9-gridjob"

getenv = USER, USE_USER, WANDB_API_KEY
environment = "JOB_MODE=h5_transferred H5_ENERGIES=${ENERGIES} H5_FILES_PER_ENERGY_RECOIL=1 WANDB_MODE=${wandb_mode} RECONSTRUCTION_MODEL_VARIANT=pairwise_channel_masking RECONSTRUCTION_RECOIL_CLASSIFICATION=1 RECONSTRUCTION_SPATIAL_TARGET_INDICES=0,1 RECONSTRUCTION_SCALAR_LOSS_WEIGHTS=1.0,1.0,1.0 RECONSTRUCTION_NUM_EPOCHS=${NUM_EPOCHS} RECONSTRUCTION_EXPECTED_H5_EVENTS_PER_FILE=${EVENTS_PER_GROUP} RECONSTRUCTION_EVAL_STEP_PERIOD=10 RECONSTRUCTION_EVAL_NUM_BATCHES=6 RECONSTRUCTION_SAVE_CHECKPOINT_PERIOD=60 RECONSTRUCTION_TOTAL_BATCH_SIZE=16 RECONSTRUCTION_DEVICE_BATCH_SIZE=4 RECONSTRUCTION_NUM_WORKERS=4 RECONSTRUCTION_MAX_OPEN_H5_FILES=12 RECONSTRUCTION_AMP_DTYPE=auto RECONSTRUCTION_SEED=42 RECONSTRUCTION_WANDB_RUN=${wandb_run} RECONSTRUCTION_WANDB_CHECKPOINT_ARTIFACTS=${wandb_artifacts} RECONSTRUCTION_WANDB_PROJECT=DELight_Reconstruction_Pairwise_Compact RECONSTRUCTION_WANDB_RUN_NAME=${RUN_NAME} RECONSTRUCTION_CHECKPOINT_DIR=artifacts/${JOB_NAME}/checkpoints/${RUN_STAMP} RECONSTRUCTION_DISABLE_TORCH_COMPILE=1 TORCHDYNAMO_DISABLE=1"

Queue
EOF
}

submit_job() {
    prepare_dataset
    transfer_files=()
    build_transfer_list transfer_files
    write_jdl "${transfer_files[@]}"

    total_bytes="$(
        printf '%s\n' "${transfer_files[@]}" \
            | grep '\.h5$' \
            | xargs stat -c '%s' \
            | awk '{sum += $1} END {print sum + 0}'
    )"
    echo "Submitting compact L40S training:"
    echo "  Real events: $((2 * 6 * EVENTS_PER_GROUP))"
    echo "  Energies: $ENERGIES"
    echo "  Epochs: $NUM_EPOCHS"
    echo "  Input transfer: $(awk -v b="$total_bytes" 'BEGIN {printf "%.2f GiB", b/1024/1024/1024}')"
    if [ -z "${WANDB_API_KEY:-}" ]; then
        echo "  W&B: disabled; checkpoints will return through Condor."
    else
        echo "  W&B: online with checkpoint artifacts."
    fi

    submit_output="$(condor_submit "$GENERATED_JDL")"
    echo "$submit_output"
    cluster="$(
        printf '%s\n' "$submit_output" \
            | sed -n 's/.*submitted to cluster \([0-9][0-9]*\).*/\1/p' \
            | tail -n 1
    )"
    if [ -n "$cluster" ]; then
        printf '%s %s\n' "$cluster" "$RUN_NAME" > "$LATEST_FILE"
    fi
}

show_status() {
    condor_q "$USER" || true
    if [ -f "$LATEST_FILE" ]; then
        read -r cluster _ < "$LATEST_FILE"
        echo
        echo "Latest compact job: $cluster"
        condor_q "$cluster" -af ClusterId ProcId JobStatus HoldReason 2>/dev/null \
            || condor_history "$cluster" -limit 1 \
                -af ClusterId ProcId JobStatus ExitCode CompletionDate 2>/dev/null \
            || true
        for suffix in out err log; do
            file="$SCRIPT_DIR/train.${cluster}.${suffix}"
            if [ -f "$file" ]; then
                echo
                echo "--- $file ---"
                tail -n 80 "$file"
            fi
        done
    fi
}

case "$ACTION" in
    prepare)
        prepare_dataset
        ;;
    dry-run)
        prepare_dataset
        transfer_files=()
        build_transfer_list transfer_files
        write_jdl "${transfer_files[@]}"
        condor_submit -append "use_x509userproxy = False" \
            -dry-run /tmp/train_compact_l40s.ad "$GENERATED_JDL"
        echo "Dry run OK: $GENERATED_JDL"
        ;;
    submit)
        submit_job
        ;;
    status)
        show_status
        ;;
    *)
        echo "Usage: $0 [prepare|dry-run|submit|status]" >&2
        exit 2
        ;;
esac
